version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable   # basic Linux image
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y curl unzip

      - run:
          name: Install kubectl
          command:
          
            KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
            echo "Downloading kubectl version: $KUBECTL_VERSION"
            curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --client

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

      - run:
          name: Configure AWS credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region=$AWS_REGION" >> ~/.aws/config

      - run:
          name: Update kubeconfig
          command: |
            aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f k8s/

workflows:
  deploy_workflow:
    jobs:
      - deploy
