name: CI - Build & Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU (for multi-arch, optional)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile          # adjust if your Dockerfile name/path differs
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask:${{ github.sha }}
        # optionally add: tags: ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask:latest
